import PDFDocument from 'pdfkit';
import type { ILessonPlan } from './model.js';
import type { ISchool } from '../School/model.js';
import type { IUser } from '../Auth/model.js';
import type { IHomework, HomeworkType } from '../Homework/model.js';

interface PopulatedPlan
  extends Omit<ILessonPlan, 'subjectId' | 'classId' | 'curriculumTopicId' | 'homeworkIds'> {
  subjectId: { name: string; code?: string };
  classId: { name: string };
  curriculumTopicId: { title: string; code?: string; description?: string } | null;
  homeworkIds: IHomework[];
}

const GRAY = '#666666';
const BLACK = '#000000';
const MARGIN = 42;
const PAGE_WIDTH = 595.28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export async function generateLessonPlanPdf(
  plan: PopulatedPlan,
  school: Pick<ISchool, 'name'>,
  teacher: Pick<IUser, 'firstName' | 'lastName'>,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: MARGIN, bufferPages: true });
  const chunks: Buffer[] = [];

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  // Header: school name
  doc.fillColor(BLACK).font('Helvetica-Bold').fontSize(14).text(school.name, { align: 'left' });
  doc.moveDown(0.2);
  doc
    .moveTo(MARGIN, doc.y)
    .lineTo(PAGE_WIDTH - MARGIN, doc.y)
    .strokeColor(GRAY)
    .stroke();
  doc.moveDown(0.8);

  // Title block
  doc.font('Helvetica-Bold').fontSize(18).fillColor(BLACK).text(plan.topic);
  if (plan.curriculumTopicId) {
    const codeSuffix = plan.curriculumTopicId.code ? ` (${plan.curriculumTopicId.code})` : '';
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(GRAY)
      .text(`CAPS: ${plan.curriculumTopicId.title}${codeSuffix}`);
  }
  doc.moveDown(0.5);

  // Meta row: teacher · class · subject · date · duration
  const date = formatLocalDate(new Date(plan.date));
  const teacherName = `${teacher.firstName} ${teacher.lastName}`;
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor(GRAY)
    .text(
      [teacherName, plan.classId.name, plan.subjectId.name, date, `${plan.durationMinutes} min`].join(
        '  \u2022  ',
      ),
    );
  doc.moveDown(1);

  // Sections
  renderSection(doc, 'Lesson Objectives', plan.objectives, 'bullet');
  renderSection(doc, 'Activities', plan.activities, 'numbered');
  renderSection(doc, 'Resources', plan.resources, 'bullet');
  renderHomeworkSection(doc, plan.homeworkIds);

  // Footer on every page
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(pages.start + i);
    doc.save();
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(GRAY)
      .text(
        `Generated by Campusly  \u2022  page ${i + 1} of ${pages.count}`,
        MARGIN,
        doc.page.height - 30,
        { align: 'center', width: CONTENT_WIDTH },
      );
    doc.restore();
  }

  doc.end();
  return done;
}

function renderSection(
  doc: PDFKit.PDFDocument,
  heading: string,
  items: string[] | undefined,
  style: 'bullet' | 'numbered',
): void {
  if (!items || items.length === 0) return;
  doc.font('Helvetica-Bold').fontSize(13).fillColor(BLACK).text(heading);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(11).fillColor(BLACK);
  items.forEach((item, i) => {
    const prefix = style === 'numbered' ? `${i + 1}. ` : '\u2022  ';
    doc.text(prefix + item, { indent: 10 });
  });
  doc.moveDown(0.8);
}

function renderHomeworkSection(doc: PDFKit.PDFDocument, homework: IHomework[]): void {
  if (!homework || homework.length === 0) return;
  doc.font('Helvetica-Bold').fontSize(13).fillColor(BLACK).text('Homework');
  doc.moveDown(0.3);

  const groups: Record<HomeworkType, IHomework[]> = {
    quiz: homework.filter((h) => h.type === 'quiz'),
    reading: homework.filter((h) => h.type === 'reading'),
    exercise: homework.filter((h) => h.type === 'exercise'),
  };

  const labels: Record<HomeworkType, string> = {
    quiz: 'Quiz',
    reading: 'Reading',
    exercise: 'Exercise',
  };

  const order: HomeworkType[] = ['quiz', 'reading', 'exercise'];
  order.forEach((type) => {
    if (groups[type].length === 0) return;
    doc.font('Helvetica-Bold').fontSize(11).fillColor(BLACK).text(`${labels[type]}:`);
    doc.font('Helvetica').fontSize(11).fillColor(BLACK);
    groups[type].forEach((hw) => {
      const details = detailForHomework(hw);
      const suffix = details ? ` \u2014 ${details}` : '';
      doc.text(`\u2022  ${hw.title}${suffix}`, { indent: 10 });
    });
    doc.moveDown(0.4);
  });
  doc.moveDown(0.4);
}

function detailForHomework(hw: IHomework): string {
  if (hw.type === 'reading' && hw.pageRange) return `pp. ${hw.pageRange}`;
  if (hw.type === 'exercise') return `${hw.exerciseQuestionIds.length} question(s)`;
  return '';
}

// Local-timezone ISO date (YYYY-MM-DD).
// toISOString() uses UTC and can produce yesterday's date for users in
// positive UTC offsets (e.g. SA UTC+2) when the timestamp is near midnight.
function formatLocalDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}
