/**
 * TikZ template data — 18 diagram templates for AI question generation.
 * Each template is a concise skeleton with placeholders for Claude to customise.
 */

import type { TikzTemplate } from './tikz-templates.js';

export const TIKZ_TEMPLATES: TikzTemplate[] = [
  // ── 1. Number Line ──────────────────────────────────────────────────────
  {
    name: 'number_line',
    diagramType: 'number_line',
    grades: [1, 9],
    packages: [],
    description: 'Horizontal number line with labelled tick marks',
    template: [
      '\\begin{tikzpicture}',
      '  \\draw[thick,->] (0,0) -- (10,0);',
      '  \\foreach \\x in {0,1,...,{XMAX}} {',
      '    \\draw (\\x,0.15) -- (\\x,-0.15) node[below]{$\\x$};',
      '  }',
      '  \\fill[red] ({VALUE},0) circle (3pt);',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 2. Cartesian Graph ──────────────────────────────────────────────────
  {
    name: 'cartesian_graph',
    diagramType: 'cartesian_graph',
    grades: [7, 12],
    packages: ['pgfplots'],
    description: 'Cartesian plane with plotted function(s)',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[axis lines=middle, xlabel=$x$, ylabel=$y$,',
      '    xmin={XMIN}, xmax={XMAX}, ymin={YMIN}, ymax={YMAX}, grid=major]',
      '    \\addplot[blue, thick, domain={DOMAIN}, samples=100] {{FUNCTION}};',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 3. Triangle ─────────────────────────────────────────────────────────
  {
    name: 'triangle',
    diagramType: 'triangle',
    grades: [4, 12],
    packages: [],
    description: 'Triangle with labelled vertices, sides and angles',
    template: [
      '\\begin{tikzpicture}',
      '  \\coordinate (A) at (0,0);',
      '  \\coordinate (B) at ({BASE},0);',
      '  \\coordinate (C) at ({CX},{CY});',
      '  \\draw[thick] (A)--(B)--(C)--cycle;',
      '  \\node[below left] at (A) {$A$};',
      '  \\node[below right] at (B) {$B$};',
      '  \\node[above] at (C) {$C$};',
      '  \\draw pic["${ANGLE}^\\circ$",draw,angle radius=8mm]{angle=B--A--C};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 4. Circle Geometry ──────────────────────────────────────────────────
  {
    name: 'circle_geometry',
    diagramType: 'circle_geometry',
    grades: [9, 12],
    packages: [],
    description: 'Circle with chords, tangents, and inscribed angles',
    template: [
      '\\begin{tikzpicture}',
      '  \\draw[thick] (0,0) circle ({RADIUS});',
      '  \\coordinate (O) at (0,0);',
      '  \\coordinate (A) at ({ANG_A}:{RADIUS});',
      '  \\coordinate (B) at ({ANG_B}:{RADIUS});',
      '  \\coordinate (C) at ({ANG_C}:{RADIUS});',
      '  \\draw (A)--(B)--(C)--cycle;',
      '  \\fill (O) circle (1.5pt) node[below]{$O$};',
      '  \\foreach \\p/\\d in {A/left,B/right,C/above}',
      '    \\node[\\d] at (\\p) {$\\p$};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 5. Venn Diagram ─────────────────────────────────────────────────────
  {
    name: 'venn_diagram',
    diagramType: 'venn_diagram',
    grades: [7, 12],
    packages: [],
    description: 'Two or three overlapping sets inside a universal set',
    template: [
      '\\begin{tikzpicture}',
      '  \\draw (0,0) rectangle (7,5) node[below left]{$\\mathcal{U}$};',
      '  \\draw[thick,fill=blue!10] (2.5,2.5) circle (1.5) node{${SET_A}};',
      '  \\draw[thick,fill=red!10] (4.5,2.5) circle (1.5) node{${SET_B}};',
      '  \\node at (3.5,2.5) {${INTERSECTION}};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 6. Trig Graph ──────────────────────────────────────────────────────
  {
    name: 'trig_graph',
    diagramType: 'trig_graph',
    grades: [10, 12],
    packages: ['pgfplots'],
    description: 'Trigonometric function graph (sin, cos, tan)',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[axis lines=middle, xlabel=$x$, ylabel=$y$,',
      '    xmin=-360, xmax=360, ymin={YMIN}, ymax={YMAX},',
      '    xtick={-360,-270,...,360}, xticklabel style={font=\\tiny},',
      '    grid=major, trig format plots=deg]',
      '    \\addplot[blue,thick,domain=-360:360,samples=200] {{TRIG_EXPR}};',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 7. Box-and-Whisker ─────────────────────────────────────────────────
  {
    name: 'box_whisker',
    diagramType: 'box_whisker',
    grades: [10, 12],
    packages: ['pgfplots'],
    description: 'Box-and-whisker plot for a data set',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[y=1cm, ytick=\\empty, xmin={XMIN}, xmax={XMAX}]',
      '    \\addplot+[boxplot prepared={',
      '      lower whisker={MIN}, lower quartile={Q1},',
      '      median={MEDIAN}, upper quartile={Q3},',
      '      upper whisker={MAX}}, ] coordinates {};',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 8. Bar Chart ───────────────────────────────────────────────────────
  {
    name: 'bar_chart',
    diagramType: 'bar_chart',
    grades: [3, 9],
    packages: ['pgfplots'],
    description: 'Vertical bar chart with categorical x-axis',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[ybar, ylabel={COUNT_LABEL},',
      '    symbolic x coords={{CATEGORIES}},',
      '    xtick=data, nodes near coords, ymin=0]',
      '    \\addplot coordinates {({CAT1},{VAL1}) ({CAT2},{VAL2}) ({CAT3},{VAL3})};',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 9. Transformation ─────────────────────────────────────────────────
  {
    name: 'transformation',
    diagramType: 'transformation',
    grades: [7, 9],
    packages: [],
    description: 'Shape with its reflection, rotation or translation',
    template: [
      '\\begin{tikzpicture}[scale=0.5]',
      '  \\draw[help lines,gray!30] (-6,-6) grid (6,6);',
      '  \\draw[->] (-6,0)--(6,0) node[right]{$x$};',
      '  \\draw[->] (0,-6)--(0,6) node[above]{$y$};',
      '  \\draw[thick,blue] {ORIGINAL_PATH} -- cycle;',
      '  \\draw[thick,red,dashed] {TRANSFORMED_PATH} -- cycle;',
      '  \\draw[dotted] {AXIS_OF_SYMMETRY};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 10. Geometric Construction ─────────────────────────────────────────
  {
    name: 'geometric_construction',
    diagramType: 'construction',
    grades: [7, 9],
    packages: ['tkz-euclide'],
    description: 'Compass-and-straightedge style construction',
    template: [
      '\\begin{tikzpicture}',
      '  \\tkzDefPoint(0,0){A} \\tkzDefPoint({LENGTH},0){B}',
      '  \\tkzDrawSegment(A,B)',
      '  \\tkzDrawCircle[dashed](A,B)',
      '  \\tkzDrawCircle[dashed](B,A)',
      '  \\tkzInterCC(A,B)(B,A) \\tkzGetPoints{C}{D}',
      '  \\tkzDrawSegments(A,C B,C)',
      '  \\tkzLabelPoints[below](A,B) \\tkzLabelPoints[above](C)',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 11. Tree Diagram ──────────────────────────────────────────────────
  {
    name: 'tree_diagram',
    diagramType: 'tree_diagram',
    grades: [10, 12],
    packages: [],
    description: 'Probability tree with branch labels',
    template: [
      '\\begin{tikzpicture}[grow=right, level distance=3cm,',
      '  level 1/.style={sibling distance=2.4cm},',
      '  level 2/.style={sibling distance=1.2cm}]',
      '  \\node{{START}}',
      '    child { node{{OUTCOME_B}}',
      '      child { node{{B_B}} edge from parent node[above]{${P_BB}$} }',
      '      child { node{{B_A}} edge from parent node[below]{${P_BA}$} }',
      '      edge from parent node[above]{${P_B}$}',
      '    }',
      '    child { node{{OUTCOME_A}}',
      '      child { node{{A_B}} edge from parent node[above]{${P_AB}$} }',
      '      child { node{{A_A}} edge from parent node[below]{${P_AA}$} }',
      '      edge from parent node[below]{${P_A}$}',
      '    };',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 12. Scatter Plot ──────────────────────────────────────────────────
  {
    name: 'scatter_plot',
    diagramType: 'scatter_plot',
    grades: [10, 12],
    packages: ['pgfplots'],
    description: 'Scatter plot with optional regression line',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[xlabel={X_LABEL}, ylabel={Y_LABEL}, grid=major,',
      '    xmin={XMIN}, xmax={XMAX}, ymin={YMIN}, ymax={YMAX}]',
      '    \\addplot[only marks, mark=*] coordinates { {DATA_POINTS} };',
      '    \\addplot[red, thick, domain={DOMAIN}] {{REGRESSION}};',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 13. Ogive ─────────────────────────────────────────────────────────
  {
    name: 'ogive',
    diagramType: 'ogive',
    grades: [11, 12],
    packages: ['pgfplots'],
    description: 'Cumulative frequency ogive curve',
    template: [
      '\\begin{tikzpicture}',
      '  \\begin{axis}[xlabel={Class boundary}, ylabel={Cumulative freq},',
      '    grid=major, ymin=0, ymax={YMAX}]',
      '    \\addplot[blue,thick,mark=*] coordinates { {CUM_POINTS} };',
      '    \\draw[dashed,red] (axis cs:{MEDIAN_X},0) -- (axis cs:{MEDIAN_X},{MEDIAN_Y});',
      '  \\end{axis}',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 14. Pie Chart ─────────────────────────────────────────────────────
  {
    name: 'pie_chart',
    diagramType: 'pie_chart',
    grades: [4, 7],
    packages: [],
    description: 'Pie chart with labelled sectors',
    template: [
      '\\begin{tikzpicture}',
      '  \\def\\radius{2}',
      '  \\def\\total{{TOTAL}}',
      '  \\pgfmathsetmacro{\\startA}{0}',
      '  \\pgfmathsetmacro{\\endA}{\\startA+{VAL1}/\\total*360}',
      '  \\fill[blue!40] (0,0) -- (\\startA:\\radius) arc(\\startA:\\endA:\\radius) -- cycle;',
      '  \\pgfmathsetmacro{\\mid}{(\\startA+\\endA)/2}',
      '  \\node at (\\mid:1.2) {{LABEL1}};',
      '  % Repeat \\fill+\\node for each sector, updating \\startA=\\endA',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 15. Basic 2D Shapes ───────────────────────────────────────────────
  {
    name: 'basic_shapes_2d',
    diagramType: 'geometric_shape',
    grades: [1, 6],
    packages: [],
    description: 'Simple 2D shape (square, rectangle, circle, etc.)',
    template: [
      '\\begin{tikzpicture}',
      '  % Square example — replace with any 2D shape',
      '  \\draw[thick] (0,0) rectangle ({WIDTH},{HEIGHT});',
      '  \\node[below] at ({WIDTH}/2,0) {{LABEL}};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 16. Shapes with Measurements ──────────────────────────────────────
  {
    name: 'shapes_with_measurements',
    diagramType: 'geometric_shape',
    grades: [4, 9],
    packages: [],
    description: 'Shape with side lengths, height and area annotations',
    template: [
      '\\begin{tikzpicture}',
      '  \\draw[thick] (0,0) -- ({BASE},0) -- ({TX},{TY}) -- cycle;',
      '  \\draw[dashed] ({TX},{TY}) -- ({TX},0) node[midway,right]{${HEIGHT}$};',
      '  \\node[below] at ({BASE}/2,0) {${BASE_LABEL}$};',
      '  \\node[left] at ({TX}/2,{TY}/2) {${SIDE_LABEL}$};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 17. 3D Shape Nets ─────────────────────────────────────────────────
  {
    name: 'shape_nets_3d',
    diagramType: 'shape_3d',
    grades: [4, 6],
    packages: [],
    description: 'Unfolded net of a 3D shape (cube, prism, etc.)',
    template: [
      '\\begin{tikzpicture}[scale=0.8]',
      '  % Cube net — cross pattern of 6 squares',
      '  \\foreach \\x/\\y in {0/1, 1/0, 1/1, 1/2, 1/3, 2/1} {',
      '    \\draw[thick] (\\x,\\y) rectangle (\\x+1,\\y+1);',
      '  }',
      '  \\node[above] at (1.5,4) {{SHAPE_NAME} net};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
  // ── 18. Pictograph ────────────────────────────────────────────────────
  {
    name: 'pictograph',
    diagramType: 'pictograph',
    grades: [1, 4],
    packages: [],
    description: 'Pictograph with icons representing counted values',
    template: [
      '\\begin{tikzpicture}',
      '  \\foreach \\row [count=\\y] in {{ROW_DATA}} {',
      '    \\node[anchor=east] at (-0.3, \\y) {\\row};',
      '    \\foreach \\i in {1,...,{COUNT}} {',
      '      \\node at (\\i, \\y) {{ICON}};',
      '    }',
      '  }',
      '  \\node[below] at (3,-0.2) {Key: {ICON} = {KEY_VALUE}};',
      '\\end{tikzpicture}',
    ].join('\n'),
  },
];
