const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });
const mongoose = require('mongoose');

const SCHOOL_ID = new mongoose.Types.ObjectId('69ce960a98ca4ee738d25416');
const CREATED_BY = new mongoose.Types.ObjectId('69ce960b98ca4ee738d25432');
const GRADE_ID = new mongoose.Types.ObjectId('69d2c1f317b8332733f72601');

let blockNum = 0;
function bid() { return 'block-' + String(++blockNum).padStart(3, '0'); }

function t(order, content) {
  return { blockId: bid(), type: 'text', order, content, points: 0, hints: [], explanation: '', metadata: {}, curriculumNodeId: null, cognitiveLevel: null };
}
function q(order, question, options, correctIndex, explanation, hints) {
  return {
    blockId: bid(), type: 'quiz', order,
    content: JSON.stringify({ question, options, correctIndex }),
    points: 1, hints: hints || [], explanation: explanation || '',
    metadata: { options, correctIndex }, curriculumNodeId: null, cognitiveLevel: null,
  };
}
function fb(order, text, blanks, explanation, hints) {
  return {
    blockId: bid(), type: 'fill_blank', order,
    content: JSON.stringify({ text, blanks }),
    points: blanks.length, hints: hints || [], explanation: explanation || '',
    metadata: { blanks }, curriculumNodeId: null, cognitiveLevel: null,
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 1: Development of Self — Healthy Lifestyle (Term 1)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch1_lesson1 = [
  t(1, '## Development of Self: Healthy Lifestyle\n\nAs a Grade 11 learner in South Africa, you are at a stage where your choices about health and lifestyle will shape your future. This chapter explores factors contributing to lifestyle diseases, strategies for prevention, treatment and support, and the long-term benefits of physical engagement.\n\n### What Is a Lifestyle Disease?\n\nA lifestyle disease (also called a non-communicable disease or NCD) is a disease linked mainly to unhealthy behaviours and environmental factors rather than to infections. Examples include cardiovascular disease, type 2 diabetes, certain cancers, and chronic respiratory diseases. In South Africa, NCDs account for more than half of all deaths, making this a critical public health issue.'),
  t(2, '### Factors Contributing to Lifestyle Diseases\n\nSeveral modifiable factors increase the risk of developing lifestyle diseases:\n\n| Factor | Description | SA Context |\n|--------|-------------|------------|\n| **Unhealthy diet** | High intake of processed foods, sugar, salt, saturated fats; low intake of fruits, vegetables, whole grains | Fast-food culture in townships and suburbs, limited access to fresh produce in rural areas |\n| **Physical inactivity** | Sedentary lifestyle, insufficient exercise | Many learners lack safe spaces for physical activity; screen time is increasing |\n| **Tobacco use** | Smoking cigarettes, hookah pipes, e-cigarettes/vaping | SA has high smoking rates; vaping is increasing among youth |\n| **Alcohol and substance abuse** | Excessive alcohol consumption, drug use | SA has one of the highest rates of alcohol-related harm globally |\n| **Unsafe sexual behaviour** | Unprotected sex, multiple partners | Contributes to HIV/AIDS and STIs, which weaken immunity and increase NCD risk |\n| **Stress** | Chronic stress, inadequate coping mechanisms | Poverty, unemployment, violence, and academic pressure are major stressors |'),
  q(3, 'Which of the following is NOT a modifiable factor contributing to lifestyle diseases?',
    ['Genetic predisposition inherited from parents', 'Unhealthy eating habits', 'Lack of physical exercise', 'Tobacco use'], 0,
    'Genetic predisposition is inherited and cannot be changed (non-modifiable). All other options are lifestyle choices that can be modified to reduce disease risk.'),
  t(4, '### Identifying and Defining Lifestyle Diseases\n\nKey lifestyle diseases to know:\n\n**Cardiovascular disease (CVD):** Diseases of the heart and blood vessels, including heart attacks and strokes. Caused by high blood pressure, high cholesterol, smoking, obesity, and physical inactivity.\n\n**Type 2 diabetes:** The body cannot use insulin effectively, leading to high blood sugar. Linked to obesity, poor diet, and inactivity. Increasingly common among young South Africans.\n\n**Cancer:** Abnormal cell growth. Risk factors include smoking (lung cancer), alcohol (liver cancer), poor diet, obesity, and UV exposure (skin cancer). SA has high rates of cervical, breast, and prostate cancer.\n\n**Chronic respiratory diseases:** Asthma, chronic obstructive pulmonary disease (COPD). Worsened by smoking, air pollution, and occupational hazards such as mining dust in SA.'),
  fb(5, 'Diseases linked to unhealthy behaviours rather than infection are called ___ diseases. The inability of the body to use insulin properly leads to type 2 ___.',
    ['lifestyle', 'diabetes'],
    'Lifestyle diseases are caused by modifiable risk factors. Type 2 diabetes results from insulin resistance, often linked to obesity and poor diet.'),
  t(6, '### Discussing the Impact of Lifestyle Diseases\n\nLifestyle diseases have far-reaching consequences:\n\n**On the individual:**\n- Reduced quality of life (pain, fatigue, limited mobility)\n- Shortened life expectancy\n- Financial burden of medication and treatment\n- Mental health impacts (depression, anxiety linked to chronic illness)\n\n**On the family:**\n- Emotional stress of caring for a sick family member\n- Financial strain from medical expenses and loss of income\n- Role reversal where children may become caregivers\n\n**On the community and country:**\n- Increased burden on the public health system\n- Lost productivity and economic output\n- Strain on social grants and welfare systems\n- In SA, the dual burden of infectious diseases (HIV/TB) alongside NCDs overwhelms healthcare facilities'),
  q(7, 'Themba is 16 and eats takeaways daily, never exercises, and spends 6 hours a day on his phone. Which lifestyle diseases is he most at risk of developing?',
    ['Cardiovascular disease and type 2 diabetes', 'Malaria and cholera', 'Tuberculosis and pneumonia', 'Measles and chickenpox'], 0,
    'Unhealthy diet and physical inactivity are primary risk factors for cardiovascular disease and type 2 diabetes. Malaria, cholera, TB, pneumonia, measles and chickenpox are infectious diseases, not lifestyle diseases.'),
  t(8, '### Prevention, Treatment, Care, and Support\n\n**Prevention strategies:**\n- Eat a balanced diet rich in fruits, vegetables, and whole grains\n- Exercise regularly (at least 30 minutes of moderate activity daily)\n- Avoid tobacco and limit alcohol consumption\n- Practise safe sexual behaviour\n- Manage stress through healthy coping mechanisms\n- Get regular health screenings\n\n**Treatment:**\n- Medical treatment prescribed by healthcare professionals\n- Lifestyle changes (diet, exercise) as part of treatment plans\n- Chronic medication for conditions like hypertension and diabetes\n\n**Care and support:**\n- Support groups for people living with chronic diseases\n- Community health workers in SA who provide education and monitoring\n- SADAG (South African Depression and Anxiety Group) for mental health support: 0800 567 567\n- Government clinics offering free chronic medication through the Essential Drug List'),
  t(9, '### Benefits of Long-Term Physical Engagement\n\nRegular physical activity over the long term provides multiple benefits:\n\n| Benefit area | Details |\n|-------------|----------|\n| **Physical health** | Strengthens heart and lungs, improves circulation, maintains healthy weight, builds bone density, boosts immune system |\n| **Mental health** | Reduces stress, anxiety, and depression; releases endorphins (natural mood boosters); improves sleep quality |\n| **Cognitive function** | Improves concentration, memory, and academic performance; increases blood flow to the brain |\n| **Social benefits** | Builds teamwork skills, expands social networks, promotes discipline and commitment |\n| **Disease prevention** | Reduces risk of cardiovascular disease, diabetes, certain cancers, and obesity |\n| **Self-esteem** | Improves body image, builds confidence, provides a sense of achievement |\n\nThe World Health Organisation recommends that adolescents get at least 60 minutes of moderate-to-vigorous physical activity daily.'),
  q(10, 'Which of the following best describes a long-term benefit of regular physical activity?',
    ['Reduced risk of cardiovascular disease and improved mental health', 'Immediate weight loss after one session', 'Guaranteed prevention of all diseases', 'No need to maintain a healthy diet'], 0,
    'Regular physical activity over the long term reduces the risk of CVD, improves mental health through endorphin release, and supports overall well-being. It does not guarantee prevention of all diseases and should be combined with healthy eating.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 2: Relationships (Term 1)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch2_lesson1 = [
  t(1, '## Relationships\n\nRelationships are a fundamental part of human life. As a Grade 11 learner, you are developing more complex relationships and need to understand the dynamics, rights, and responsibilities that come with them.\n\n### Different Types of Relationships\n\nRelationships can be categorised as follows:\n\n| Type | Description | Examples |\n|------|-------------|----------|\n| **Family relationships** | Bonds with family members | Parent-child, sibling, extended family, blended families |\n| **Friendships** | Voluntary bonds based on mutual affection | School friends, neighbourhood friends, online friends |\n| **Romantic relationships** | Intimate bonds involving emotional and sometimes physical closeness | Dating, courtship, marriage |\n| **Professional/Formal** | Relationships within structured environments | Teacher-learner, employer-employee, coach-player |\n| **Community relationships** | Bonds within broader social groups | Neighbours, religious communities, cultural groups |'),
  t(2, '### Rights and Responsibilities in Relationships\n\nEvery relationship involves both rights and responsibilities. The South African Constitution (Bill of Rights, Chapter 2) protects many of these:\n\n**Your rights in relationships:**\n- The right to be treated with dignity and respect (Section 10)\n- The right to privacy (Section 14)\n- The right to freedom and security of the person (Section 12) — no one may abuse you physically or emotionally\n- The right to say no — to physical intimacy, to peer pressure, to any unwanted behaviour\n- The right to equality and non-discrimination (Section 9)\n\n**Your responsibilities in relationships:**\n- Treat others with respect and dignity\n- Communicate honestly and openly\n- Respect boundaries — both your own and others\n- Support and encourage your partner, friends, and family\n- Take responsibility for your actions and their impact on others\n- Seek help when a relationship becomes harmful'),
  q(3, 'Naledi tells her boyfriend that she is not ready for a physical relationship. He pressures her, saying "If you loved me, you would." Which of Naledi\'s constitutional rights is being violated?',
    ['Freedom and security of the person (Section 12)', 'Freedom of expression (Section 16)', 'Freedom of religion (Section 15)', 'Right to education (Section 29)'], 0,
    'Section 12 of the Bill of Rights protects freedom and security of the person, including the right to make decisions about your own body. Pressuring someone into physical intimacy violates this right.'),
  t(4, '### Qualities Sought in Relationships\n\nHealthy relationships are built on key qualities:\n\n**Trust:** Being able to rely on the other person. Trust is built over time through consistent, honest behaviour.\n\n**Respect:** Valuing the other person as an equal, accepting differences, and honouring boundaries.\n\n**Communication:** Sharing thoughts and feelings openly, listening actively, and resolving disagreements constructively.\n\n**Empathy:** Understanding and sharing another person\'s feelings. This requires active listening and suspending judgement.\n\n**Honesty:** Being truthful even when it is difficult. Honesty builds trust and prevents misunderstandings.\n\n**Commitment:** Being willing to invest time and effort into the relationship. This means being there during good times and bad.\n\n**Support:** Encouraging each other\'s goals, dreams, and personal growth.'),
  fb(5, 'The ability to understand and share another person\'s feelings is called ___. The right to make decisions about your own body is protected by Section ___ of the Bill of Rights.',
    ['empathy', '12'],
    'Empathy is the ability to put yourself in someone else\'s shoes. Section 12 of the South African Bill of Rights protects freedom and security of the person.'),
  t(6, '### Detrimental Relationships\n\nNot all relationships are healthy. Detrimental (harmful) relationships include:\n\n**Abusive relationships:**\n- Physical abuse: hitting, slapping, pushing\n- Emotional abuse: insults, manipulation, gaslighting, threats\n- Sexual abuse: any unwanted sexual contact or coercion\n- Financial abuse: controlling someone\'s access to money\n\n**Controlling relationships:**\n- One partner makes all decisions\n- Isolating you from friends and family\n- Monitoring your phone, social media, or movements\n- Using jealousy as an excuse for control\n\n**Toxic friendships:**\n- Friends who consistently bring you down or undermine your confidence\n- Friendships based on peer pressure to engage in risky behaviour\n- One-sided friendships where only one person puts in effort\n\n**Warning signs:** Constant criticism, isolation from loved ones, walking on eggshells, feeling afraid or anxious, loss of self-esteem.'),
  q(7, 'Sipho\'s girlfriend checks his phone daily, gets angry when he spends time with friends, and threatens to break up if he does not reply to messages immediately. This behaviour is an example of:',
    ['A controlling relationship', 'A healthy relationship with high standards', 'Normal teenage jealousy that will pass', 'A sign of deep love and commitment'], 0,
    'Monitoring a partner\'s phone, isolating them from friends, and using threats are hallmarks of a controlling relationship. These behaviours are harmful and should not be normalised as love or caring.'),
  t(8, '### Getting Help for Harmful Relationships\n\nIf you or someone you know is in a harmful relationship:\n\n**Immediate steps:**\n- Talk to a trusted adult (parent, teacher, school counsellor)\n- Contact a helpline:\n  - Childline: 0800 055 555\n  - Stop Gender Violence Helpline: 0800 150 150\n  - Lifeline SA: 0861 322 322\n  - SAPS Emergency: 10111\n\n**Legal protection in SA:**\n- The Domestic Violence Act (Act 116 of 1998) provides for protection orders\n- The Sexual Offences Act protects against sexual abuse and exploitation\n- The Children\'s Act protects children under 18 from abuse and neglect\n\n**Remember:**\n- Abuse is NEVER the victim\'s fault\n- Leaving an abusive relationship takes courage and support\n- It is okay to ask for help — it is a sign of strength, not weakness'),
  t(9, '### Appropriate Expression of Feelings in Relationships\n\nExpressing your feelings appropriately is essential for healthy relationships:\n\n**Using "I" statements:**\n- Instead of: "You never listen to me!" (accusatory)\n- Say: "I feel unheard when I am interrupted" (expresses your feelings without blame)\n\n**Choosing the right time and place:**\n- Do not discuss serious issues in public or when emotions are running high\n- Wait until both parties are calm and have privacy\n\n**Respecting cultural contexts:**\n- In South Africa\'s diverse culture, different communities may have different norms around emotional expression\n- Some cultures emphasise stoicism; others are more openly expressive\n- Understanding these differences prevents misunderstandings\n\n**Healthy expression includes:**\n- Naming your emotions specifically ("I feel disappointed" rather than "I feel bad")\n- Taking responsibility for your feelings\n- Listening to the other person\'s perspective\n- Finding solutions together rather than assigning blame'),
  q(10, 'Which of the following is the best example of appropriately expressing feelings in a relationship?',
    ['"I feel hurt when plans are cancelled without explanation because I value our time together"', '"You always cancel on me — you obviously do not care about me"', '"Whatever, it is fine" (while clearly upset)', '"I am going to tell everyone what you did to me"'], 0,
    'The first option uses an "I" statement, identifies the specific feeling and trigger, and explains why it matters. The other options are accusatory, passive-aggressive, or threatening.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 3: Study Skills (Term 1)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch3_lesson1 = [
  t(1, '## Study Skills\n\nEffective studying is a skill that can be learned and improved. Understanding your study style, using the right learning strategies, and preparing for exams will help you perform at your best in Grade 11 and beyond.\n\n### Study Styles and Learning Preferences\n\nEvery learner processes information differently. Understanding your preferred style helps you study more efficiently:\n\n| Style | How you learn best | Effective strategies |\n|-------|-------------------|---------------------|\n| **Visual** | Through seeing (diagrams, charts, videos) | Mind maps, colour-coded notes, flowcharts, posters, watching educational videos |\n| **Auditory** | Through hearing (lectures, discussions) | Reading aloud, recording notes and replaying, group discussions, verbal explanations |\n| **Reading/Writing** | Through text (reading, note-taking) | Summarising, rewriting notes, making lists, reading multiple sources |\n| **Kinaesthetic** | Through doing (hands-on, movement) | Practising problems, role-play, building models, walking while revising |'),
  t(2, '### Learning Strategies for Grade 11\n\nGrade 11 introduces more complex content across all subjects. These strategies will help:\n\n**Active recall:** After reading a section, close the book and write down everything you remember. This forces your brain to retrieve information, strengthening memory.\n\n**Spaced repetition:** Review material at increasing intervals. Study a topic today, review it after 2 days, then after 5 days, then after 10 days. This is far more effective than cramming.\n\n**The Pomodoro Technique:** Study for 25 minutes, take a 5-minute break. After 4 cycles, take a longer 20-minute break. This prevents burnout and maintains focus.\n\n**Elaborative interrogation:** Ask "why?" and "how?" about everything you study. Do not just memorise facts — understand the reasoning behind them.\n\n**Interleaving:** Mix different topics or subjects in one study session rather than studying one topic for hours. This improves your ability to distinguish between concepts.'),
  q(3, 'Ayanda studies Accounting for 4 hours straight, then does the same for Physical Science the next day. Which study technique would improve her approach?',
    ['Interleaving — mixing different subjects in one session', 'Studying only one subject per week', 'Reading through notes once before the exam', 'Highlighting every line in the textbook'], 0,
    'Interleaving involves alternating between topics or subjects during a study session. This helps the brain make connections and improves long-term retention compared to massed practice of one subject.'),
  t(4, '### Exam Writing Skills\n\nKnowing the content is only half the battle. You also need to know how to present your answers effectively:\n\n**Understanding command words:**\n\n| Command word | What it requires |\n|-------------|------------------|\n| **Define** | Give the exact meaning of the term |\n| **Identify** | Name or point out specific items |\n| **Describe** | Give a detailed account of features or characteristics |\n| **Explain** | Give reasons or make the meaning clear |\n| **Discuss** | Present different aspects, arguments for and against |\n| **Evaluate** | Make a judgement using evidence, weigh pros and cons |\n| **Analyse** | Break down into parts and examine each |\n| **Compare** | Show similarities AND differences |\n| **Distinguish** | Show only the differences |'),
  t(5, '### Exam Writing Tips\n\n**Before the exam:**\n- Read through the entire paper before answering\n- Allocate time per section based on mark allocation\n- Start with sections you feel most confident about\n\n**During the exam:**\n- Read each question twice before answering\n- Underline key command words\n- Use the mark allocation as a guide: 4 marks = 4 distinct points\n- Write in full sentences for discussion questions\n- Use bullet points for listing or identifying\n- Answer ALL questions — never leave a question blank\n\n**After the exam:**\n- Review your answers if time allows\n- Check that you have answered all questions\n- Ensure your name and exam number are on every page'),
  fb(6, 'The study technique of testing yourself on material rather than re-reading is called ___. Reviewing material at increasing intervals is called ___ repetition.',
    ['active recall', 'spaced'],
    'Active recall strengthens memory by forcing retrieval. Spaced repetition distributes study over time, which is more effective than cramming.'),
  t(7, '### Creating an Effective Study Plan\n\nA study plan helps you manage your time, cover all subjects, and reduce stress:\n\n**Steps to create your study plan:**\n1. **List all subjects** and identify which need the most attention\n2. **Check your exam timetable** and work backwards from each exam date\n3. **Allocate time blocks** — study your most difficult subjects during your peak focus time (morning for most people)\n4. **Include breaks** — the brain needs rest to consolidate learning\n5. **Set specific goals** for each session ("Complete Chapter 4 summary" not just "Study Life Orientation")\n6. **Build in flexibility** — life happens; allow catch-up time\n7. **Review weekly** — adjust the plan based on your progress\n\n**Study environment:**\n- Find a quiet, well-lit space\n- Remove distractions (phone on silent, social media logged out)\n- Have all materials ready before you start\n- If you do not have a quiet space at home, use the school library or a community library'),
  q(8, 'Bongani sets a study goal of "Study for 3 hours tonight." Why is this NOT an effective study goal?',
    ['It is vague and does not specify what content to cover or what outcome to achieve', 'Three hours is too short for effective studying', 'Goals should only focus on one subject', 'Study goals are unnecessary for effective studying'], 0,
    'Effective study goals are specific and measurable, such as "Complete past paper 2 on healthy lifestyles and score above 70%." Vague goals like "study for 3 hours" lead to unfocused studying.'),
  t(9, '### Dealing with Study Challenges\n\nCommon challenges Grade 11 learners face and how to overcome them:\n\n**Procrastination:**\n- Break large tasks into small, manageable steps\n- Use the "two-minute rule" — if it takes less than two minutes, do it now\n- Reward yourself after completing tasks\n\n**Lack of motivation:**\n- Connect your studies to your career goals\n- Study with a motivated friend or study group\n- Visualise your success\n\n**Distractions:**\n- Use apps that block social media during study time\n- Tell family and friends when you are studying so they respect your time\n- If home is too noisy, find an alternative study space\n\n**Anxiety about exams:**\n- Preparation is the best antidote to anxiety\n- Practise deep breathing exercises before and during exams\n- Remember: one exam does not define your worth\n- Speak to a teacher or counsellor if anxiety is overwhelming'),
  q(10, 'Which combination of study strategies would be MOST effective for preparing for a Grade 11 Life Orientation test?',
    ['Active recall with spaced repetition, practising past papers, and using mind maps for visual topics', 'Reading through notes once the night before the test', 'Highlighting every paragraph and hoping to remember it', 'Studying for 8 hours straight without breaks'], 0,
    'The combination of active recall, spaced repetition, past papers, and visual aids engages multiple learning strategies and is supported by research as the most effective approach to studying.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 4: Careers and Career Choices (Term 1)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch4_lesson1 = [
  t(1, '## Careers and Career Choices\n\nGrade 11 is a critical year for career planning. The subjects you are taking now, the skills you are developing, and the decisions you make will shape your post-school path. This chapter covers competencies, career advertisements, CV writing, job interviews, and exploring your career interests.\n\n### Competencies, Abilities, and Ethics in the Workplace\n\n**Competencies** are the skills, knowledge, and behaviours needed to perform effectively in a job:\n\n| Competency type | Description | Examples |\n|----------------|-------------|----------|\n| **Technical skills** | Job-specific knowledge and abilities | Computer literacy, accounting, welding, teaching methodology |\n| **Soft skills** | Interpersonal and communication abilities | Teamwork, leadership, time management, conflict resolution |\n| **Emotional intelligence** | Ability to manage your own emotions and understand others | Empathy, self-awareness, stress management |\n| **Ethical competence** | Acting with integrity and professionalism | Honesty, accountability, respect for diversity |'),
  t(2, '### Workplace Ethics\n\nEthics refers to the moral principles that guide behaviour in the workplace:\n\n**Key ethical principles:**\n- **Integrity:** Being honest and having strong moral principles\n- **Accountability:** Taking responsibility for your actions\n- **Confidentiality:** Protecting private information\n- **Respect:** Treating colleagues, clients, and the public with dignity\n- **Fairness:** Treating everyone equitably regardless of race, gender, or background\n\n**Unethical behaviour in the workplace includes:**\n- Fraud and corruption (stealing company resources, accepting bribes)\n- Discrimination and harassment\n- Nepotism (hiring family members regardless of qualifications)\n- Plagiarism and dishonesty\n- Arriving late, leaving early, or not doing your work\n\nIn South Africa, the Companies Act and King IV Report on Corporate Governance set standards for ethical business conduct.'),
  q(3, 'A company hires the manager\'s nephew for a position even though more qualified candidates applied. This is an example of:',
    ['Nepotism', 'Affirmative action', 'Fair recruitment', 'Employment equity'], 0,
    'Nepotism is the practice of favouring family members or friends in hiring decisions regardless of their qualifications. This is unethical and differs from affirmative action, which aims to correct historical imbalances.'),
  t(4, '### Reading and Responding to Career Advertisements\n\nJob advertisements contain key information you must understand:\n\n**Typical components of a job advert:**\n- **Job title:** The name of the position\n- **Company name and description:** Who the employer is\n- **Key responsibilities:** What the job involves\n- **Requirements:** Qualifications, experience, and skills needed\n- **Remuneration:** Salary or salary range (sometimes listed as "market-related")\n- **Application instructions:** How to apply, deadline, required documents\n- **Contact details:** Where to send your application\n\n**Reading between the lines:**\n- "Self-starter" = you must be able to work independently\n- "Team player" = collaboration is essential\n- "Deadline-driven" = the job involves pressure and strict timelines\n- "Market-related salary" = the salary is competitive but not disclosed'),
  t(5, '### CV Writing (Curriculum Vitae)\n\nYour CV is your first impression on a potential employer. It must be professional, clear, and honest.\n\n**Structure of a CV:**\n\n1. **Personal details:** Full name, contact number, email address, physical address\n2. **Personal statement/Profile:** 2-3 sentences summarising who you are and what you offer\n3. **Education:** Schools attended, highest grade completed, subjects (list from most recent)\n4. **Work experience:** Any part-time work, volunteering, or learnerships (list from most recent)\n5. **Skills:** Computer skills, languages spoken, driver\'s licence\n6. **Achievements:** Awards, leadership positions, sports achievements\n7. **References:** 2-3 people who can vouch for your character and abilities (ask permission first)\n\n**CV tips:**\n- Keep it to 2 pages maximum\n- Use a professional email address (not coolguy123@email.com)\n- Proofread carefully — spelling errors create a bad impression\n- Tailor your CV to each job you apply for\n- Never lie on your CV — it will catch up with you'),
  fb(6, 'A document summarising your qualifications, skills, and experience for job applications is called a ___. Hiring family members regardless of qualifications is called ___.',
    ['CV', 'nepotism'],
    'A CV (curriculum vitae) is a professional document used in job applications. Nepotism is the unethical practice of favouring relatives in hiring decisions.'),
  t(7, '### Job Interview Skills\n\nAn interview is your opportunity to make a personal impression and demonstrate why you are the right candidate:\n\n**Before the interview:**\n- Research the company thoroughly\n- Prepare answers to common questions:\n  - "Tell me about yourself"\n  - "Why do you want this position?"\n  - "What are your strengths and weaknesses?"\n  - "Where do you see yourself in five years?"\n- Plan your outfit (professional, neat, appropriate)\n- Know the location and arrive 10-15 minutes early\n\n**During the interview:**\n- Greet the interviewer with a firm handshake and eye contact\n- Speak clearly and confidently\n- Listen carefully to questions and answer specifically\n- Use examples to illustrate your points\n- Ask thoughtful questions about the role\n\n**After the interview:**\n- Thank the interviewer for their time\n- Follow up with a brief thank-you email if possible\n- Reflect on what went well and what you could improve'),
  q(8, 'Zanele has a job interview tomorrow. Which of the following should she do to prepare?',
    ['Research the company and practise answers to common interview questions', 'Arrive 30 minutes late to appear relaxed and casual', 'Make up qualifications to impress the interviewer', 'Spend the evening on social media and hope for the best'], 0,
    'Thorough preparation — including company research, practising answers, and planning logistics — is the key to a successful interview. Arriving late, lying, or failing to prepare are all likely to result in rejection.'),
  t(9, '### Exploring Career Interests\n\nChoosing a career is one of the most important decisions you will make. It should align with your interests, abilities, values, and personality:\n\n**Self-assessment questions:**\n- What subjects do I enjoy most? What am I good at?\n- What activities make me lose track of time?\n- Do I prefer working with people, data, things, or ideas?\n- Do I want to work indoors or outdoors?\n- Is salary, job satisfaction, or work-life balance most important to me?\n\n**Career exploration resources in South Africa:**\n- National Career Advice Portal (NCAP): www.careerhelp.org.za\n- SAQA (South African Qualifications Authority): www.saqa.org.za\n- Department of Higher Education and Training: www.dhet.gov.za\n- University open days and career expos\n- Job shadowing and mentoring programmes\n- PACE Career Centre\n\n**Post-school options:**\n- University (bachelor\'s degree — requires a bachelor\'s pass in NSC)\n- University of Technology (diplomas and BTech degrees)\n- TVET Colleges (vocational and technical qualifications)\n- Learnerships and apprenticeships (earn while you learn)\n- Entrepreneurship (starting your own business)'),
  q(10, 'Which of the following is the BEST approach to choosing a career?',
    ['Assessing your interests, abilities, and values, then researching careers that match', 'Choosing the career with the highest salary regardless of your interests', 'Following exactly what your parents want you to do', 'Waiting until after matric to think about it'], 0,
    'A well-informed career choice considers your personal interests, strengths, values, and personality alongside practical factors like job availability and earning potential. Starting early gives you time to explore and prepare.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 5: Democracy and Human Rights (Term 2)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch5_lesson1 = [
  t(1, '## Democracy and Human Rights\n\nSouth Africa is a constitutional democracy where the rights of all citizens are protected by the Constitution and the Bill of Rights. This chapter examines the role of media, social media and digital citizenship, discrimination, and how sports contribute to nation building.\n\n### The Role of Media in a Democratic Society\n\nMedia plays a vital role in democracy:\n\n**Functions of the media:**\n- **Informing the public:** Reporting news, events, and government activities\n- **Watchdog role:** Holding government and powerful institutions accountable\n- **Platform for debate:** Allowing different voices and opinions to be heard\n- **Educating citizens:** Providing information that helps people make informed decisions\n- **Agenda setting:** Influencing which issues the public thinks about\n\n**Media freedom in SA:**\n- Section 16 of the Bill of Rights protects freedom of expression, including freedom of the press\n- The South African Broadcasting Corporation (SABC) is the public broadcaster\n- Independent media outlets provide alternative perspectives\n- Media freedom is NOT absolute — it does not protect propaganda for war, incitement to violence, or hate speech'),
  t(2, '### Social Media and Digital Footprint\n\nSocial media has transformed how we communicate, access information, and participate in democracy:\n\n**Benefits of social media:**\n- Enables civic participation (petitions, campaigns, awareness)\n- Connects people across geographic boundaries\n- Provides a platform for marginalised voices\n- Facilitates access to educational resources\n\n**Risks of social media:**\n- Spread of misinformation and fake news\n- Echo chambers (only seeing views you already agree with)\n- Privacy violations and data harvesting\n- Cyberbullying and online harassment\n- Addiction and negative impact on mental health\n\n**Your digital footprint:**\nEverything you post, share, like, or comment on creates a permanent digital record. This includes:\n- Social media posts and photos\n- Comments on forums and articles\n- Online purchases and website visits\n- Messages on platforms\n\nFuture employers, universities, and bursary providers may search your name online. A negative digital footprint can cost you opportunities.'),
  q(3, 'Lindiwe shares a news article on social media without checking if it is true. The article turns out to be fake and causes panic in her community. What concept does this illustrate?',
    ['The spread of misinformation through social media', 'Responsible digital citizenship', 'The watchdog role of media', 'Freedom of expression without limitations'], 0,
    'Sharing unverified information contributes to the spread of misinformation. Responsible digital citizenship requires verifying information before sharing it.'),
  t(4, '### Cyber Wellness, Safety, and Bullying\n\n**Cyber wellness** is the positive well-being of internet users. It involves understanding the risks and taking steps to protect yourself:\n\n**Cyberbullying:**\n- Sending threatening or hurtful messages\n- Sharing embarrassing photos without consent\n- Creating fake profiles to harass someone\n- Excluding someone from online groups deliberately\n- Spreading rumours online\n\n**Cyberbullying in SA law:**\n- The Cybercrimes Act (Act 19 of 2020) criminalises cyberbullying, especially against children\n- Schools have a duty to address cyberbullying that affects learners\n- Victims can report cyberbullying to the South African Cyber Security Hub: 0800 222 447\n\n**Cyber safety tips:**\n- Never share passwords or personal information online\n- Use strong, unique passwords for each account\n- Enable two-factor authentication\n- Think before you post — would you say it to the person\'s face?\n- Report and block cyberbullies\n- Keep evidence of cyberbullying (screenshots)'),
  fb(5, 'The permanent record of your online activity is called your digital ___. The South African law that criminalises cyberbullying is the ___ Act.',
    ['footprint', 'Cybercrimes'],
    'Your digital footprint is the trail of data you leave online. The Cybercrimes Act (2020) addresses cybercrimes including cyberbullying.'),
  t(6, '### Discrimination\n\nDiscrimination means treating someone differently or unfairly based on a characteristic such as race, gender, religion, disability, or sexual orientation.\n\n**Forms of discrimination:**\n- **Direct discrimination:** Openly treating someone differently (e.g., refusing to hire someone because of their race)\n- **Indirect discrimination:** Applying a rule that appears neutral but disadvantages a particular group\n- **Hate speech:** Speech that attacks or demeans a group based on protected characteristics\n\n**The Bill of Rights and discrimination:**\n- Section 9 (Equality) prohibits unfair discrimination on grounds including race, gender, sex, pregnancy, marital status, ethnic or social origin, colour, sexual orientation, age, disability, religion, conscience, belief, culture, language, and birth\n- The Promotion of Equality and Prevention of Unfair Discrimination Act (PEPUDA/Equality Act) provides mechanisms to address discrimination\n- The South African Human Rights Commission (SAHRC) investigates complaints of discrimination\n\n**Discrimination in SA context:**\n- Apartheid was a system of institutionalised racial discrimination\n- Despite its end in 1994, the effects of apartheid discrimination continue (inequality, poverty, spatial segregation)\n- Xenophobia (discrimination against foreign nationals) remains a concern\n- Gender-based violence reflects deep-seated gender discrimination'),
  q(7, 'A school requires all learners to attend a specific religious assembly. Muslim and Hindu learners feel excluded. What type of discrimination is this?',
    ['Indirect discrimination based on religion', 'Direct discrimination based on race', 'Affirmative action', 'Cultural preservation'], 0,
    'Requiring attendance at a specific religious assembly appears neutral but disproportionately disadvantages learners of other faiths. This is indirect discrimination based on religion, violating Section 15 (freedom of religion) and Section 9 (equality).'),
  t(8, '### Sports and Nation Building\n\nSport has played a powerful role in building South Africa as a nation:\n\n**Historical examples:**\n- The 1995 Rugby World Cup united the nation when Nelson Mandela wore the Springbok jersey\n- The 2010 FIFA World Cup showcased South Africa to the world and fostered national pride\n- Bafana Bafana, the Proteas, and Banyana Banyana bring diverse communities together\n\n**How sports build the nation:**\n- Create a shared identity across racial, cultural, and language divides\n- Provide role models from all backgrounds\n- Promote values of teamwork, discipline, fair play, and respect\n- Economic benefits: tourism, job creation, infrastructure development\n\n**Challenges in SA sport:**\n- Historical racial imbalances in sports opportunities and resources\n- Transformation policies aim to ensure representation across all racial groups\n- Access to facilities remains unequal between urban and rural areas\n- Gender inequality in sports coverage, funding, and opportunities\n- Corruption in sports administration'),
  t(9, '### Ideologies and Beliefs\n\nAn ideology is a set of beliefs or ideas that shape how a person or group sees the world. In a democracy, different ideologies coexist:\n\n**Key concepts:**\n- **Democracy:** Government by the people; protects individual rights and freedoms\n- **Socialism:** Emphasises collective ownership and equality of outcome\n- **Capitalism:** Emphasises private ownership and free markets\n- **Ubuntu:** African philosophy of shared humanity — "I am because we are"\n- **Feminism:** Advocacy for gender equality\n- **Conservatism:** Emphasises tradition, stability, and gradual change\n\n**In SA:**\n- The Constitution balances individual rights with social responsibility\n- Different political parties represent different ideological positions\n- Freedom of belief is protected (Section 15), but no ideology may override the Bill of Rights\n- Respecting ideological diversity is essential for a functioning democracy'),
  q(10, 'Which of the following best explains how the Bill of Rights limits freedom of expression in South Africa?',
    ['It does not protect propaganda for war, incitement to violence, or hate speech', 'It allows the government to censor any media it disagrees with', 'It only protects the freedom of expression of majority groups', 'There are no limitations on freedom of expression in SA'], 0,
    'Section 16 of the Bill of Rights protects freedom of expression but specifically excludes propaganda for war, incitement of imminent violence, and advocacy of hatred based on race, ethnicity, gender, or religion that constitutes incitement to cause harm.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 6: Social and Environmental Responsibility (Term 2)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch6_lesson1 = [
  t(1, '## Social and Environmental Responsibility\n\nAs citizens of South Africa, we have a responsibility to contribute to our communities and protect our environment. This chapter explores the role of government, community services, environmental programmes, and how to create a personal mission and vision statement.\n\n### Government Responsibilities\n\nSouth Africa has three levels of government, each with distinct responsibilities:\n\n| Level | Structure | Key responsibilities |\n|-------|----------|---------------------|\n| **National** | Parliament, President, Cabinet | Defence, foreign affairs, national health and education policy, SAPS, SARS, social grants |\n| **Provincial** | Premier, MECs, Provincial Legislature | Provincial roads, hospitals, schools, housing, agriculture, provincial planning |\n| **Local** | Municipalities (metros, districts, local) | Water supply, electricity, refuse removal, local roads, sanitation, community facilities |'),
  t(2, '### How Government Serves Communities\n\nGovernment delivers services through various mechanisms:\n\n**Social grants:** SASSA administers grants including the Child Support Grant (R530/month), Old Age Pension, Disability Grant, and Foster Care Grant. Over 18 million South Africans receive social grants.\n\n**Public healthcare:** Government clinics and hospitals provide free or subsidised healthcare. The National Health Insurance (NHI) aims to provide universal health coverage.\n\n**Education:** Public schools, TVET colleges, and universities receive government funding. No-fee schools serve the poorest communities. NSFAS provides funding for higher education.\n\n**Housing:** The RDP (Reconstruction and Development Programme) housing programme provides subsidised housing to qualifying citizens.\n\n**Challenges:**\n- Service delivery protests occur when communities feel government is not meeting their needs\n- Corruption diverts resources from service delivery\n- Infrastructure backlogs, especially in rural areas and informal settlements\n- Load-shedding reflects failures in energy planning and maintenance'),
  q(3, 'Which level of government is responsible for providing water supply and refuse removal to communities?',
    ['Local government (municipalities)', 'National government', 'Provincial government', 'All three levels equally'], 0,
    'Local government (municipalities) is responsible for basic services including water supply, electricity distribution, refuse removal, sanitation, and local roads. These are listed in Schedule 5B of the Constitution.'),
  t(4, '### Community Services\n\nCommunity services are organised efforts to address social needs and improve quality of life:\n\n**Types of community services in SA:**\n- **Non-governmental organisations (NGOs):** Organisations like Gift of the Givers, Habitat for Humanity SA, and local soup kitchens that provide aid and support\n- **Faith-based organisations:** Churches, mosques, and temples that run feeding schemes, youth programmes, and shelters\n- **Community policing forums (CPFs):** Partnerships between SAPS and community members to address crime\n- **Volunteer programmes:** Organisations that coordinate volunteers for community projects\n- **Stokvels:** Traditional savings groups that pool resources for community members\n\n**The role of youth in community service:**\n- Volunteering builds skills, empathy, and a sense of purpose\n- Community service can be included on your CV\n- Many universities and bursaries value community involvement\n- Young people bring energy, creativity, and fresh perspectives to community challenges'),
  t(5, '### Environmental Programmes and Responsibility\n\nSouth Africa faces significant environmental challenges:\n\n**Key environmental issues:**\n- **Water scarcity:** SA is a water-scarce country; droughts and pollution threaten water security\n- **Air pollution:** Industrial emissions, vehicle exhaust, and burning of fossil fuels\n- **Land degradation:** Overgrazing, deforestation, mining, and urbanisation\n- **Waste management:** Illegal dumping, inadequate recycling infrastructure\n- **Climate change:** Rising temperatures, more extreme weather events, sea-level rise\n- **Biodiversity loss:** Poaching, habitat destruction, invasive species\n\n**Environmental programmes in SA:**\n- Working for Water: Removes invasive alien plants and creates jobs\n- Working on Fire: Manages wildfire risk and provides employment\n- Expanded Public Works Programme (EPWP): Green economy projects\n- National Recycling Forum: Promotes recycling and waste reduction\n- SA National Parks (SANParks): Manages protected areas and biodiversity'),
  fb(6, 'The government agency that administers social grants in South Africa is called ___. South Africa has ___ levels of government.',
    ['SASSA', 'three'],
    'SASSA (South African Social Security Agency) administers social grants. South Africa has three levels of government: national, provincial, and local.'),
  t(7, '### Your Environmental Responsibility\n\nAs an individual, you can make a difference:\n\n**Reduce, Reuse, Recycle:**\n- Reduce water and electricity consumption\n- Reuse containers, bags, and materials\n- Separate waste for recycling (paper, plastic, glass, metal)\n\n**At school:**\n- Start or join an environmental club\n- Organise clean-up campaigns\n- Create a school vegetable garden\n- Reduce paper waste — use both sides\n\n**In your community:**\n- Report illegal dumping to your municipality\n- Participate in river and beach clean-ups\n- Plant trees and indigenous plants\n- Support local food gardens\n\n**Advocacy:**\n- Raise awareness about environmental issues on social media\n- Attend public participation processes on environmental decisions\n- Support organisations fighting for environmental justice\n- Section 24 of the Bill of Rights guarantees the right to an environment that is not harmful to health or well-being'),
  q(8, 'Section 24 of the South African Bill of Rights protects which of the following?',
    ['The right to an environment that is not harmful to health or well-being', 'The right to free housing for all citizens', 'The right to unlimited use of natural resources', 'The right to ignore environmental regulations'], 0,
    'Section 24 guarantees everyone the right to an environment that is not harmful to their health or well-being and requires the state to take measures to protect the environment for present and future generations.'),
  t(9, '### Personal Mission and Vision Statement\n\nA personal mission and vision statement helps you define your purpose and goals:\n\n**Vision statement:** Describes where you want to be in the future. It is aspirational and forward-looking.\n- Example: "I envision a career in environmental law where I can protect South Africa\'s natural heritage and ensure environmental justice for all communities."\n\n**Mission statement:** Describes what you do NOW to work toward your vision. It is action-oriented.\n- Example: "I commit to studying diligently, volunteering in community environmental projects, and developing my leadership skills to prepare for a career in environmental law."\n\n**How to write yours:**\n1. Reflect on your values: What matters most to you?\n2. Identify your strengths: What are you good at?\n3. Consider your passions: What makes you feel alive?\n4. Think about impact: How do you want to contribute to society?\n5. Write it down: Keep it concise, personal, and meaningful\n6. Review regularly: Your mission and vision may evolve as you grow'),
  q(10, 'What is the key difference between a personal vision statement and a personal mission statement?',
    ['A vision statement describes your future aspirations; a mission statement describes what you do now to achieve them', 'They are the same thing with different names', 'A vision statement is for companies only, not individuals', 'A mission statement is about money; a vision statement is about happiness'], 0,
    'A vision statement is future-oriented (where you want to be), while a mission statement is present-oriented (what you are doing now to get there). Both are important for personal goal-setting.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 7: Lifestyle Diseases and Health (Term 3)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch7_lesson1 = [
  t(1, '## Lifestyle Diseases and Health\n\nThis chapter takes a deeper look at the human factors causing ill-health and the major lifestyle diseases affecting South Africans. Understanding these factors and diseases empowers you to make healthier choices and support those affected.\n\n### Human Factors Causing Ill-Health\n\n**Poor eating habits:**\n- Excessive consumption of processed foods high in sugar, salt, and unhealthy fats\n- Skipping meals, especially breakfast\n- Overeating or undereating\n- Reliance on fast food and sugary drinks\n- In SA, food insecurity in some communities leads to malnutrition, while urbanisation drives overconsumption of processed foods\n\n**Smoking and tobacco use:**\n- Cigarettes contain over 7 000 chemicals, including at least 70 known carcinogens\n- Smoking damages the lungs, heart, blood vessels, and nearly every organ\n- Secondhand smoke is also harmful, especially to children\n- E-cigarettes/vaping are not safe alternatives — they contain nicotine and harmful chemicals\n- In SA, the Tobacco Products Control Act regulates tobacco advertising and smoking in public places'),
  t(2, '### Substance Abuse\n\nSubstance abuse is a major cause of ill-health in South Africa:\n\n| Substance | Health effects | SA context |\n|-----------|---------------|------------|\n| **Alcohol** | Liver disease, brain damage, cardiovascular disease, foetal alcohol spectrum disorder (FASD) | SA has one of the highest rates of hazardous drinking globally; FASD rates in some SA regions are the highest in the world |\n| **Cannabis (dagga)** | Impaired memory, reduced motivation, respiratory issues, mental health problems | Legalised for private use (2018) but still harmful, especially for developing teenage brains |\n| **Methamphetamine (tik)** | Severe dental damage, psychosis, heart problems, extreme weight loss | Major problem in Western Cape and increasingly in other provinces |\n| **Nyaope/whoonga** | Severe addiction, organ damage, HIV risk from shared needles | Prevalent in Gauteng and KwaZulu-Natal |\n| **Prescription drug abuse** | Dependency, organ damage, overdose | Codeine-containing medications are commonly abused |'),
  q(3, 'Which of the following statements about e-cigarettes (vaping) is TRUE?',
    ['They contain nicotine and harmful chemicals and are not a safe alternative to smoking', 'They are completely safe because they do not produce smoke', 'They are recommended by doctors as a healthy habit', 'They contain no addictive substances'], 0,
    'E-cigarettes contain nicotine (which is addictive) and produce aerosols with harmful chemicals. They are not a safe alternative to traditional cigarettes, despite being marketed as such.'),
  t(4, '### Unsafe Sexual Behaviour\n\nUnsafe sexual behaviour is a significant health risk, particularly in South Africa:\n\n**Risks include:**\n- HIV/AIDS infection — SA has the largest HIV epidemic in the world (approximately 8 million people living with HIV)\n- Sexually transmitted infections (STIs): chlamydia, gonorrhoea, syphilis, herpes, HPV\n- Unintended pregnancy and its social and educational consequences\n- Emotional and psychological harm\n\n**Safe sexual behaviour:**\n- Abstinence is the only 100% effective method of preventing STIs and pregnancy\n- Consistent and correct condom use significantly reduces risk\n- Getting tested regularly for STIs and HIV\n- Being in a mutually faithful relationship with a partner who has tested negative\n- Male medical circumcision reduces HIV risk by approximately 60%\n- PrEP (pre-exposure prophylaxis) is available for people at high risk of HIV\n\n**SA resources:**\n- Free condoms are available at government clinics and many public places\n- loveLife provides youth-friendly sexual health services and education\n- Centres for Disease Control and Prevention supports HIV prevention programmes in SA'),
  fb(5, 'South Africa has the largest ___ epidemic in the world. The only 100% effective method of preventing STIs and pregnancy is ___.',
    ['HIV', 'abstinence'],
    'South Africa has approximately 8 million people living with HIV, the largest epidemic globally. While abstinence is the only fully effective prevention method, consistent condom use significantly reduces risk.'),
  t(6, '### Cancer\n\nCancer occurs when abnormal cells grow uncontrollably and can invade other tissues:\n\n**Common cancers in SA:**\n- Cervical cancer (leading cancer among SA women — largely preventable through HPV vaccination and screening)\n- Breast cancer\n- Prostate cancer (most common cancer among SA men)\n- Lung cancer (strongly linked to smoking)\n- Kaposi sarcoma (linked to HIV/AIDS)\n\n**Risk factors:**\n- Smoking (lung, throat, bladder, and other cancers)\n- Excessive alcohol (liver, breast, oesophageal cancers)\n- Obesity and poor diet\n- Excessive sun exposure without protection (skin cancer)\n- HPV infection (cervical and other cancers)\n- Genetic factors\n\n**Prevention:**\n- HPV vaccination for girls (available free in SA public schools)\n- Regular screening (Pap smears, breast self-examinations, prostate checks)\n- Avoid tobacco and limit alcohol\n- Maintain a healthy weight and eat a balanced diet\n- Use sunscreen and avoid excessive sun exposure\n- CANSA (Cancer Association of South Africa) provides education and support: 0800 22 66 22'),
  t(7, '### Tuberculosis (TB)\n\nTB is both an infectious disease and a disease worsened by lifestyle factors:\n\n**Key facts about TB in SA:**\n- SA has one of the highest TB rates in the world\n- TB and HIV form a deadly combination — people with HIV are much more likely to develop active TB\n- Drug-resistant TB (MDR-TB and XDR-TB) is a growing concern\n- TB thrives in overcrowded, poorly ventilated conditions\n\n**Lifestyle factors that increase TB risk:**\n- Smoking damages the lungs and weakens defences against TB\n- Alcohol abuse weakens the immune system\n- Malnutrition reduces the body\'s ability to fight infection\n- HIV infection severely compromises immunity\n\n**Prevention and treatment:**\n- Complete the full course of TB medication (6-9 months) — stopping early creates drug resistance\n- Good ventilation in homes and public spaces\n- Covering mouth when coughing, proper hand hygiene\n- BCG vaccination given at birth provides some protection\n- Free TB treatment is available at all government clinics in SA'),
  q(8, 'Why is it critical to complete the full course of TB medication, even after symptoms improve?',
    ['Stopping early allows surviving bacteria to develop drug resistance', 'The medication tastes good and should be enjoyed', 'Symptoms improving means the disease is getting worse', 'TB medication has no side effects and is harmless to take indefinitely'], 0,
    'Incomplete TB treatment kills weaker bacteria but allows stronger ones to survive and multiply, potentially developing into multi-drug resistant TB (MDR-TB) or extensively drug-resistant TB (XDR-TB), which are much harder and more expensive to treat.'),
  t(9, '### Cardiovascular Disease (CVD) and STIs\n\n**Cardiovascular disease:**\nCVD includes diseases of the heart and blood vessels (heart attacks, strokes, hypertension):\n- Leading cause of death globally and a major killer in SA\n- Risk factors: high blood pressure, high cholesterol, smoking, obesity, diabetes, physical inactivity, stress\n- Prevention: regular exercise, healthy diet, avoiding smoking, managing stress, regular blood pressure checks\n\n**Sexually Transmitted Infections (STIs):**\nSTIs are infections spread through sexual contact:\n\n| STI | Symptoms | Treatment |\n|-----|----------|----------|\n| **Chlamydia** | Often no symptoms; discharge, pain during urination | Antibiotics |\n| **Gonorrhoea** | Discharge, painful urination, pelvic pain | Antibiotics |\n| **Syphilis** | Painless sores, rash, organ damage if untreated | Antibiotics (penicillin) |\n| **Herpes** | Painful blisters, recurring outbreaks | Antiviral medication (no cure) |\n| **HPV** | Genital warts, cervical cancer risk | HPV vaccine for prevention; warts can be treated |\n| **HIV/AIDS** | Weakened immune system, opportunistic infections | Antiretroviral therapy (ART) — no cure but manageable |'),
  t(10, '### HIV/AIDS in South Africa\n\nHIV/AIDS remains the most significant public health challenge in South Africa:\n\n**Key statistics:**\n- Approximately 8 million South Africans are living with HIV\n- SA has the largest antiretroviral therapy (ART) programme in the world\n- New infections have declined but remain high, especially among young women aged 15-24\n\n**Living with HIV:**\n- ART allows people with HIV to live long, healthy lives\n- An undetectable viral load means HIV cannot be transmitted sexually (U=U: Undetectable = Untransmittable)\n- Stigma and discrimination remain barriers to testing and treatment\n- Disclosure is a personal decision protected by the right to privacy\n\n**Support and resources:**\n- Treatment Action Campaign (TAC): advocacy for access to treatment\n- South African National AIDS Council (SANAC): coordinates the national HIV response\n- Free HIV testing and ART at all government clinics\n- National AIDS Helpline: 0800 012 322\n\n**Your role:**\n- Get tested regularly\n- Do not stigmatise or discriminate against people living with HIV\n- Practise safe sexual behaviour\n- Support friends and family who are affected'),
  q(11, 'What does "U=U" (Undetectable = Untransmittable) mean in the context of HIV?',
    ['A person with an undetectable viral load on ART cannot transmit HIV sexually', 'HIV has been cured and is no longer a concern', 'Universal testing means universal treatment', 'Unprotected sex is safe if you feel healthy'], 0,
    'U=U is a scientifically proven concept: when a person living with HIV takes ART consistently and achieves an undetectable viral load, they cannot transmit HIV through sexual contact. This does not mean HIV is cured — ART must be taken for life.'),
  fb(12, 'The combination of TB and ___ is particularly deadly because the latter weakens the immune system. South Africa has the largest ___ therapy programme in the world.',
    ['HIV', 'antiretroviral'],
    'HIV weakens the immune system, making TB infection much more likely to progress to active disease. South Africa runs the world\'s largest ART programme to manage HIV.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 8: Labour Laws and the World of Work (Term 3)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch8_lesson1 = [
  t(1, '## Labour Laws and the World of Work\n\nUnderstanding labour laws protects your rights as a worker and helps you navigate the world of work. South Africa has comprehensive labour legislation that governs employment relationships.\n\n### The Job Contract (Employment Contract)\n\nAn employment contract is a legally binding agreement between an employer and an employee:\n\n**What must be included:**\n- Full names of employer and employee\n- Job title and description of duties\n- Place of work\n- Working hours (ordinary hours and overtime arrangements)\n- Remuneration (salary/wages), how it is calculated, and payment frequency\n- Leave entitlements (annual leave, sick leave, family responsibility leave)\n- Notice period for termination\n- Start date and duration (permanent, fixed-term, or temporary)\n\n**Important notes:**\n- Even verbal agreements are legally binding, but written contracts provide better protection\n- An employer must provide a written contract or written particulars within two months of employment starting\n- Never sign a contract without reading and understanding it fully\n- If you do not understand something, ask for clarification or seek legal advice'),
  t(2, '### Workers Rights in South Africa\n\nSouth African workers have extensive rights protected by law:\n\n**Constitutional rights (Bill of Rights):**\n- Section 23: Everyone has the right to fair labour practices\n- The right to form and join a trade union\n- The right to strike\n- The right to fair and safe working conditions\n\n**Key rights under labour legislation:**\n- Right to a written employment contract\n- Right to minimum wage (National Minimum Wage: currently R27.58 per hour)\n- Right to reasonable working hours (max 45 hours/week for most workers)\n- Right to overtime pay (1.5 times normal rate)\n- Right to leave: 21 consecutive days annual leave, 36 days sick leave in a 3-year cycle, 3 days family responsibility leave per year\n- Right to not be unfairly dismissed\n- Right to a safe and healthy workplace\n- Right to equal pay for work of equal value\n- Protection against unfair discrimination in the workplace'),
  q(3, 'Thabo works 50 hours per week and is paid R25 per hour with no overtime. Which of his rights is being violated?',
    ['His right to the national minimum wage and to overtime pay for hours exceeding 45 per week', 'His right to annual leave only', 'No rights are being violated as the employer sets the terms', 'His right to join a trade union'], 0,
    'Thabo is being paid below the National Minimum Wage (R27.58/hour) and is not receiving overtime pay for the 5 hours exceeding the 45-hour weekly maximum. Both violate the Basic Conditions of Employment Act.'),
  t(4, '### The Labour Relations Act (LRA), No. 66 of 1995\n\nThe LRA is the primary law governing labour relations in South Africa:\n\n**Purpose:**\n- Promote economic development, social justice, labour peace, and democratisation of the workplace\n- Regulate the rights of trade unions, employers, and employer organisations\n- Provide a framework for collective bargaining\n- Regulate strikes and lockouts\n- Prevent and resolve labour disputes\n\n**Key provisions:**\n- **Unfair dismissal:** An employer may not dismiss an employee without a fair reason and a fair procedure\n- **Unfair labour practices:** Includes unfair conduct related to promotion, demotion, training, or benefits\n- **Freedom of association:** Workers have the right to form or join trade unions\n- **Collective bargaining:** Unions negotiate wages and conditions on behalf of members\n- **Dispute resolution:** The CCMA (Commission for Conciliation, Mediation and Arbitration) resolves disputes between employers and employees\n\n**The CCMA:**\n- A free service that helps resolve workplace disputes\n- Handles conciliation (trying to reach agreement) and arbitration (making a binding decision)\n- Workers can refer disputes to the CCMA without needing a lawyer\n- Contact: 0861 16 16 16 or visit www.ccma.org.za'),
  fb(5, 'The law that governs labour relations including unfair dismissal and collective bargaining is the ___ Act. The body that resolves workplace disputes for free is the ___.',
    ['Labour Relations', 'CCMA'],
    'The Labour Relations Act (LRA) is the primary labour relations legislation. The CCMA (Commission for Conciliation, Mediation and Arbitration) provides free dispute resolution services.'),
  t(6, '### The Employment Equity Act (EEA), No. 55 of 1998\n\nThe EEA aims to achieve equity in the workplace:\n\n**Purpose:**\n- Promote equal opportunity and fair treatment through elimination of unfair discrimination\n- Implement affirmative action measures to redress disadvantages experienced by designated groups\n\n**Designated groups:**\n- Black people (African, Coloured, Indian)\n- Women\n- People with disabilities\n\n**What the EEA requires:**\n- Employers must eliminate unfair discrimination in employment policies and practices\n- Designated employers (50+ employees or above a certain turnover) must prepare and implement employment equity plans\n- Designated employers must report to the Department of Employment and Labour on their progress\n\n**Important distinction:**\n- Affirmative action is NOT unfair discrimination — it is a legal and constitutional mechanism to correct historical imbalances\n- Section 9(2) of the Constitution explicitly allows for measures to promote equality for previously disadvantaged groups'),
  t(7, '### The Basic Conditions of Employment Act (BCEA), No. 75 of 1997\n\nThe BCEA sets minimum employment conditions:\n\n| Condition | Requirement |\n|-----------|-------------|\n| **Working hours** | Maximum 45 hours per week (9 hours/day for 5-day week, 8 hours/day for 6-day week) |\n| **Overtime** | Maximum 10 hours/week; paid at 1.5 times normal rate (or 2 times on Sundays/public holidays) |\n| **Annual leave** | 21 consecutive days per year (or 1 day for every 17 days worked) |\n| **Sick leave** | 36 days in a 3-year cycle (equivalent to 6 weeks in first 6 months) |\n| **Family responsibility leave** | 3 days per year (for birth of child, illness of child, death of close family) |\n| **Maternity leave** | 4 consecutive months (UIF pays a portion of salary) |\n| **Notice period** | 1 week (0-6 months), 2 weeks (6-12 months), 4 weeks (1+ year) |\n| **Child labour** | Prohibited under age 15; restricted for ages 15-17 |'),
  q(8, 'Nomsa has worked at a company for 2 years. She is being dismissed with one week\'s notice. Is this lawful?',
    ['No, she is entitled to 4 weeks notice because she has worked for more than one year', 'Yes, one week is always sufficient notice', 'No, she cannot be dismissed at all after 2 years', 'Yes, notice periods are optional in South Africa'], 0,
    'Under the BCEA, an employee who has worked for more than one year is entitled to at least 4 weeks notice. One week notice applies only to employees in their first 6 months of employment.'),
  t(9, '### Trade Unions, Equity and Redress\n\n**Trade unions:**\n- Organisations formed by workers to protect their interests and rights\n- Major SA trade unions: COSATU, FEDUSA, NACTU, SAFTU\n- Functions: negotiate wages, represent members in disputes, advocate for better conditions\n- The right to join a union is protected by Section 23 of the Bill of Rights and the LRA\n- Union members pay monthly subscriptions (union dues)\n\n**Equity and redress in the workplace:**\n- Historical context: Apartheid created massive inequalities in employment opportunities, education, and wealth\n- Redress aims to correct these historical injustices through:\n  - Affirmative action policies\n  - Broad-Based Black Economic Empowerment (B-BBEE)\n  - Skills development programmes\n  - Bursaries and learnerships targeting previously disadvantaged groups\n- The goal is not to disadvantage any group but to create genuine equality of opportunity'),
  t(10, '### The Recruitment Process\n\nUnderstanding the recruitment process prepares you for entering the job market:\n\n**Steps in the recruitment process:**\n1. **Job analysis:** Employer identifies the need for a position and defines the role\n2. **Job advertisement:** Position is advertised (newspapers, websites, social media)\n3. **Application:** Candidates submit CVs, cover letters, and required documents\n4. **Shortlisting:** Employer selects candidates who meet minimum requirements\n5. **Interviews:** Shortlisted candidates are interviewed (may include tests or assessments)\n6. **Selection:** The most suitable candidate is chosen based on qualifications, experience, and fit\n7. **Appointment:** Successful candidate receives a job offer and signs a contract\n8. **Induction:** New employee is oriented to the workplace, policies, and colleagues\n\n**Your rights during recruitment:**\n- You may not be discriminated against on grounds of race, gender, disability, pregnancy, etc.\n- Interview questions must be relevant to the job\n- You have the right to know the outcome of your application'),
  q(11, 'Which South African law specifically aims to correct historical workplace imbalances through affirmative action?',
    ['The Employment Equity Act (EEA)', 'The Labour Relations Act (LRA)', 'The Basic Conditions of Employment Act (BCEA)', 'The Companies Act'], 0,
    'The Employment Equity Act specifically addresses affirmative action and the elimination of unfair discrimination in the workplace to redress historical imbalances.'),
  t(12, '### Work Ethics\n\nWork ethics are the values and principles that guide your conduct in the workplace:\n\n**Key work ethics:**\n- **Punctuality:** Arriving on time shows respect for others and commitment to your responsibilities\n- **Reliability:** Doing what you say you will do, meeting deadlines, being consistent\n- **Professionalism:** Dressing appropriately, communicating respectfully, maintaining confidentiality\n- **Honesty and integrity:** Being truthful, not stealing time or resources, admitting mistakes\n- **Accountability:** Taking responsibility for your actions and their consequences\n- **Continuous learning:** Being willing to learn new skills and improve\n- **Respect:** Treating colleagues, clients, and superiors with dignity regardless of their position\n\n**Why work ethics matter:**\n- They build your professional reputation\n- They create a positive and productive work environment\n- They lead to career advancement and opportunities\n- They contribute to the success of the organisation\n- In a country with high unemployment, good work ethics help you stand out and keep your job'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHAPTER 9: Revision (Term 3-4)
// ═══════════════════════════════════════════════════════════════════════════════
blockNum = 0;
const ch9_lesson1 = [
  t(1, '## Revision: Grade 11 Life Orientation\n\nThis chapter consolidates the key concepts from all chapters covered during the year. Use this as a study guide to prepare for your assessments.\n\n### Term 1 Revision: Development of Self — Healthy Lifestyle\n\n**Key concepts:**\n- Lifestyle diseases (NCDs) are linked to unhealthy behaviours, not infections\n- Major risk factors: unhealthy diet, physical inactivity, smoking, alcohol abuse, unsafe sexual behaviour, stress\n- Major lifestyle diseases: cardiovascular disease, type 2 diabetes, cancer, chronic respiratory diseases\n- Prevention focuses on lifestyle modification: balanced diet, regular exercise, avoiding tobacco and excess alcohol\n- Long-term physical engagement benefits: physical health, mental health, cognitive function, social benefits, disease prevention, self-esteem\n- SA context: dual burden of NCDs and infectious diseases, SADAG support, government clinic chronic medication'),
  t(2, '### Term 1 Revision: Relationships\n\n**Key concepts:**\n- Types of relationships: family, friendships, romantic, professional, community\n- Rights in relationships: dignity (Section 10), privacy (Section 14), freedom and security (Section 12), equality (Section 9)\n- Responsibilities: respect, honesty, communication, supporting others, taking accountability\n- Qualities for healthy relationships: trust, respect, communication, empathy, honesty, commitment, support\n- Detrimental relationships: abusive, controlling, toxic — recognise warning signs\n- Legal protection: Domestic Violence Act, Sexual Offences Act, Children\'s Act\n- Appropriate expression of feelings: "I" statements, right time and place, cultural awareness\n- Support: Childline 0800 055 555, Stop GBV 0800 150 150'),
  q(3, 'Which section of the Bill of Rights protects the right to human dignity?',
    ['Section 10', 'Section 9', 'Section 12', 'Section 16'], 0,
    'Section 10 of the Bill of Rights states: "Everyone has inherent dignity and the right to have their dignity respected and protected."'),
  t(4, '### Term 1 Revision: Study Skills\n\n**Key concepts:**\n- Learning styles: visual, auditory, reading/writing, kinaesthetic\n- Effective study strategies: active recall, spaced repetition, Pomodoro Technique, elaborative interrogation, interleaving\n- Command words: define, identify, describe, explain, discuss, evaluate, analyse, compare, distinguish\n- Exam writing: read the whole paper first, allocate time by marks, underline key words, answer all questions\n- Study plan: list subjects, check timetable, allocate time blocks, set specific goals, include breaks, review weekly\n- Dealing with challenges: procrastination (break tasks down), motivation (connect to goals), distractions (eliminate), anxiety (prepare and breathe)'),
  t(5, '### Term 1 Revision: Careers and Career Choices\n\n**Key concepts:**\n- Competencies: technical skills, soft skills, emotional intelligence, ethical competence\n- Workplace ethics: integrity, accountability, confidentiality, respect, fairness\n- Unethical behaviour: fraud, corruption, nepotism, discrimination, plagiarism\n- CV structure: personal details, personal statement, education, work experience, skills, achievements, references\n- Job interview: research the company, prepare for common questions, dress professionally, arrive early, follow up\n- Career exploration: self-assessment, NCAP, SAQA, DHET, university open days\n- Post-school options: university, UoT, TVET, learnerships, entrepreneurship'),
  fb(6, 'The five main conflict resolution styles are competing, compromising, ___, collaborating, and avoiding. The CCMA stands for Commission for Conciliation, ___ and Arbitration.',
    ['accommodating', 'Mediation'],
    'The five conflict resolution styles are: competing, compromising, accommodating, collaborating, and avoiding. CCMA = Commission for Conciliation, Mediation and Arbitration.'),
  t(7, '### Term 2 Revision: Democracy and Human Rights\n\n**Key concepts:**\n- Media functions: informing, watchdog, platform for debate, educating, agenda setting\n- Freedom of expression (Section 16): protected but limited — no propaganda for war, incitement to violence, or hate speech\n- Digital footprint: permanent record of online activity; future employers check\n- Cyberbullying: criminalised under the Cybercrimes Act (2020)\n- Cyber safety: strong passwords, two-factor authentication, think before posting, report and block\n- Discrimination: direct, indirect, hate speech — prohibited by Section 9 and PEPUDA\n- Sports and nation building: 1995 RWC, 2010 FIFA WC, transformation challenges\n- Ideologies: democracy, socialism, capitalism, ubuntu, feminism, conservatism'),
  t(8, '### Term 2 Revision: Social and Environmental Responsibility\n\n**Key concepts:**\n- Three levels of government: national (Parliament), provincial (Premier), local (municipalities)\n- Local government provides: water, electricity, refuse removal, sanitation, local roads\n- Social grants administered by SASSA: Child Support, Old Age, Disability, Foster Care\n- Community services: NGOs, faith-based organisations, CPFs, stokvels, volunteering\n- Environmental issues: water scarcity, air pollution, land degradation, waste, climate change, biodiversity loss\n- Environmental programmes: Working for Water, Working on Fire, EPWP, SANParks\n- Section 24: right to a healthy environment\n- Personal mission (what you do now) and vision (where you want to be) statements'),
  q(9, 'Which of the following correctly matches the labour law with its main purpose?',
    ['LRA: labour relations and dispute resolution; EEA: workplace equity and affirmative action; BCEA: minimum employment conditions', 'LRA: minimum wages; EEA: dispute resolution; BCEA: affirmative action', 'LRA: health and safety; EEA: working hours; BCEA: trade union registration', 'All three laws serve the same purpose with different names'], 0,
    'The LRA governs labour relations, unfair dismissal, and dispute resolution. The EEA addresses workplace equity and affirmative action. The BCEA sets minimum conditions of employment like working hours, leave, and notice periods.'),
  t(10, '### Term 3 Revision: Lifestyle Diseases and Health\n\n**Key concepts:**\n- Human factors causing ill-health: poor eating, smoking, substance abuse, unsafe sexual behaviour\n- Substances: alcohol (liver disease, FASD), cannabis (memory/motivation), tik (psychosis), nyaope (severe addiction)\n- Cancer: cervical (HPV vaccine), breast, prostate, lung (smoking); prevention through screening and lifestyle\n- TB: high rates in SA, TB-HIV co-infection, complete full course of medication, drug resistance\n- CVD: heart attacks, strokes, hypertension; prevention through exercise, diet, no smoking\n- STIs: chlamydia, gonorrhoea, syphilis, herpes, HPV, HIV/AIDS\n- HIV/AIDS: 8 million living with HIV in SA, ART, U=U, free testing at clinics\n- Support: CANSA 0800 22 66 22, AIDS Helpline 0800 012 322, loveLife'),
  t(11, '### Term 3 Revision: Labour Laws and the World of Work\n\n**Key concepts:**\n- Employment contract: must include job description, hours, salary, leave, notice period\n- Key laws: LRA (labour relations, CCMA), EEA (equity, affirmative action), BCEA (minimum conditions)\n- BCEA conditions: 45 hours/week max, overtime at 1.5x, 21 days annual leave, 36 days sick leave per 3-year cycle\n- National Minimum Wage: R27.58/hour\n- Trade unions: COSATU, FEDUSA, NACTU, SAFTU — right to join protected by Section 23\n- CCMA: free dispute resolution, conciliation and arbitration\n- Recruitment process: job analysis, advertisement, application, shortlisting, interview, selection, appointment, induction\n- Work ethics: punctuality, reliability, professionalism, integrity, accountability, continuous learning, respect'),
  q(12, 'A Grade 11 learner is preparing for their Life Orientation exam. Which approach would BEST help them study effectively?',
    ['Create a study plan with specific goals, use active recall and spaced repetition, and practise past papers', 'Read through all the notes once the night before', 'Only study the topics they find interesting', 'Memorise definitions without understanding the concepts'], 0,
    'Effective studying combines planning (study plan with goals), evidence-based techniques (active recall, spaced repetition), and practice (past papers). Simply reading notes once, selective studying, or rote memorisation without understanding are all ineffective approaches.'),
];

// ═══════════════════════════════════════════════════════════════════════════════
// INSERT EVERYTHING
// ═══════════════════════════════════════════════════════════════════════════════

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  const db = mongoose.connection.db;

  // Look up or create the Life Orientation subject
  let subjectDoc = await db.collection('subjects').findOne({ name: /Life Orientation/i, schoolId: SCHOOL_ID });
  let SUBJECT_ID;

  if (subjectDoc) {
    SUBJECT_ID = subjectDoc._id;
    console.log('Found Life Orientation subject:', String(SUBJECT_ID));
  } else {
    const result = await db.collection('subjects').insertOne({
      name: 'Life Orientation',
      code: 'LO',
      schoolId: SCHOOL_ID,
      isDeleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    SUBJECT_ID = result.insertedId;
    console.log('Created Life Orientation subject:', String(SUBJECT_ID));
  }

  const now = new Date();
  const baseDoc = {
    schoolId: SCHOOL_ID,
    createdBy: CREATED_BY,
    gradeId: GRADE_ID,
    subjectId: SUBJECT_ID,
    type: 'lesson',
    status: 'approved',
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
    __v: 0,
  };

  const chapters = [
    {
      title: 'Chapter 1: Development of Self — Healthy Lifestyle',
      description: 'Factors contributing to lifestyle diseases, identifying and defining lifestyle diseases, discussing their impact, prevention/treatment/care/support strategies, and long-term benefits of physical engagement.',
      order: 1,
      lessons: [
        { title: 'Development of Self: Healthy Lifestyle', description: 'Factors contributing to lifestyle diseases, identifying and defining NCDs, discussing their impact on individuals, families, and communities, prevention/treatment/care/support strategies, and long-term benefits of physical engagement.', blocks: ch1_lesson1, term: 1 },
      ],
    },
    {
      title: 'Chapter 2: Relationships',
      description: 'Different types of relationships, rights and responsibilities in relationships, qualities sought, detrimental relationships, and appropriate expression of feelings.',
      order: 2,
      lessons: [
        { title: 'Relationships', description: 'Types of relationships (family, friendships, romantic, professional, community), rights and responsibilities protected by the Bill of Rights, qualities for healthy relationships, detrimental and abusive relationships, and appropriate expression of feelings.', blocks: ch2_lesson1, term: 1 },
      ],
    },
    {
      title: 'Chapter 3: Study Skills',
      description: 'Study styles and learning preferences, learning strategies, exam writing skills, and creating an effective study plan.',
      order: 3,
      lessons: [
        { title: 'Study Skills', description: 'Study styles (visual, auditory, reading/writing, kinaesthetic), learning strategies (active recall, spaced repetition, Pomodoro, interleaving), exam writing skills and command words, and creating an effective study plan.', blocks: ch3_lesson1, term: 1 },
      ],
    },
    {
      title: 'Chapter 4: Careers and Career Choices',
      description: 'Competencies, abilities and ethics in the workplace, reading career advertisements, CV writing, job interview skills, and exploring career interests.',
      order: 4,
      lessons: [
        { title: 'Careers and Career Choices', description: 'Workplace competencies (technical, soft, emotional intelligence, ethical), workplace ethics, reading and responding to career advertisements, CV writing, job interview skills, and exploring career interests and post-school options.', blocks: ch4_lesson1, term: 1 },
      ],
    },
    {
      title: 'Chapter 5: Democracy and Human Rights',
      description: 'Role of media in a democratic society, social media and digital footprint, cyber wellness/safety/bullying, discrimination, Bill of Rights, sports and nation building, and ideologies.',
      order: 5,
      lessons: [
        { title: 'Democracy and Human Rights', description: 'Role of media in democracy, social media and digital footprint, cyber wellness and the Cybercrimes Act, discrimination and PEPUDA, Bill of Rights protections, sports and nation building in SA, and ideologies and beliefs.', blocks: ch5_lesson1, term: 2 },
      ],
    },
    {
      title: 'Chapter 6: Social and Environmental Responsibility',
      description: 'Government responsibilities at national, provincial and local level, community services, environmental programmes, and personal mission/vision statements.',
      order: 6,
      lessons: [
        { title: 'Social and Environmental Responsibility', description: 'Three levels of government and their responsibilities, SASSA and social grants, community services and NGOs, environmental challenges and programmes in SA, individual environmental responsibility, and creating personal mission and vision statements.', blocks: ch6_lesson1, term: 2 },
      ],
    },
    {
      title: 'Chapter 7: Lifestyle Diseases and Health',
      description: 'Human factors causing ill-health (poor eating, smoking, substance abuse, unsafe sexual behaviour), lifestyle diseases (cancer, TB, cardiovascular disease, STIs, HIV/AIDS).',
      order: 7,
      lessons: [
        { title: 'Lifestyle Diseases and Health', description: 'Human factors causing ill-health, substance abuse in SA, unsafe sexual behaviour, cancer prevention and screening, TB and drug resistance, cardiovascular disease, STIs, and HIV/AIDS in South Africa.', blocks: ch7_lesson1, term: 3 },
      ],
    },
    {
      title: 'Chapter 8: Labour Laws and the World of Work',
      description: 'Job contracts, workers rights, Labour Relations Act, Employment Equity Act, Basic Conditions of Employment Act, trade unions, equity and redress, recruitment process, and work ethics.',
      order: 8,
      lessons: [
        { title: 'Labour Laws and the World of Work', description: 'Employment contracts, workers rights, LRA and the CCMA, Employment Equity Act and affirmative action, BCEA minimum conditions, trade unions, equity and redress, the recruitment process, and work ethics.', blocks: ch8_lesson1, term: 3 },
      ],
    },
    {
      title: 'Chapter 9: Revision',
      description: 'Comprehensive revision of all Grade 11 Life Orientation topics across Terms 1, 2, and 3, with key concepts, definitions, and practice questions.',
      order: 9,
      lessons: [
        { title: 'Revision', description: 'Comprehensive revision covering healthy lifestyle, relationships, study skills, careers, democracy and human rights, social and environmental responsibility, lifestyle diseases and health, and labour laws.', blocks: ch9_lesson1, term: 3 },
      ],
    },
  ];

  const textbookChapters = [];
  let totalLessons = 0;

  for (const ch of chapters) {
    const resourceIds = [];
    for (const lesson of ch.lessons) {
      const res = await db.collection('contentresources').insertOne({
        ...baseDoc,
        title: lesson.title,
        description: lesson.description,
        blocks: lesson.blocks,
        term: lesson.term,
        curriculumNodeId: null,
      });
      resourceIds.push(res.insertedId);
      totalLessons++;
      console.log('  Inserted: ' + lesson.title + ' (' + lesson.blocks.length + ' blocks)');
    }

    textbookChapters.push({
      id: new mongoose.Types.ObjectId().toString(),
      title: ch.title,
      description: ch.description,
      order: ch.order,
      curriculumNodeId: null,
      resources: resourceIds.map((id, i) => ({ resourceId: id, order: i })),
    });
  }

  // Create textbook
  const textbook = await db.collection('textbooks').insertOne({
    title: 'Grade 11 Life Orientation \u2014 CAPS Textbook',
    description: 'Complete CAPS-aligned textbook covering Development of Self, Relationships, Study Skills, Careers, Democracy and Human Rights, Social and Environmental Responsibility, Lifestyle Diseases, and Labour Laws for the Grade 11 Life Orientation curriculum.',
    schoolId: SCHOOL_ID,
    gradeId: GRADE_ID,
    subjectId: SUBJECT_ID,
    status: 'published',
    chapters: textbookChapters,
    createdBy: CREATED_BY,
    isDeleted: false,
    createdAt: now,
    updatedAt: now,
    __v: 0,
  });

  console.log('\n========================================');
  console.log('  TEXTBOOK: Grade 11 Life Orientation');
  console.log('  ID: ' + String(textbook.insertedId));
  console.log('  Chapters: ' + textbookChapters.length);
  console.log('  Lessons: ' + totalLessons);
  console.log('========================================');

  await mongoose.disconnect();
}

main().catch(err => { console.error(err); process.exit(1); });
